---
title: "HW1"
author: "Yingzhen Wang"
date: "1/27/2022"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo= TRUE, warning=FALSE, message=FALSE)
```


## R Code

```{r}
library(dplyr)
library(ggplot2)
data(diamonds)
head(diamonds)
set.seed(74)
small.diamonds <- diamonds[sample(nrow(diamonds),500),]
head(small.diamonds)

p_dp <- ggplot(data = small.diamonds, mapping = aes(x = carat, y = price, color = clarity))
p_dp <- p_dp + geom_point(aes(size = depth/100),alpha=.5,shape=16) + geom_smooth(method = "loess")
p_dp <- p_dp + theme_minimal() + xlab("weight of the diamond (carat)") + ylab("price of the diamond (dollar)") 
p_dp <- p_dp + theme(legend.position = c(0.87, 0.25))


line_ends <- ggplot_build(p_dp)$data[[2]] %>%
         group_by(colour) %>% 
         filter(x==max(x))
line_ends$clarity <- diamonds %>% pull(clarity) %>% unique() %>% as.character() %>% sort()

p_dp <- p_dp +  ggrepel::geom_label_repel(data = line_ends, 
                         aes(x = line_ends$x, 
                             y = line_ends$y, 
                             label = clarity), 
                         nudge_x = 1,
                         label.size=NA,
                         fill = alpha(c("white"),0))
p_dp <- p_dp + guides(size=guide_legend(title="depth (hundreds)"),
                      color="none")

```

## Save Figure as pdf

```{r save as pdf}
pdf("Diamonds.pdf", heigh=8, width=12)
print(p_dp)
dev.off()
```

## Display Figure in HTLM

```{r diplay}
p_dp
```